unique_ids:
  assets:
    standard-page.html: WR6IH34P47V752JIXKHFNBNAAEH4HSH5
    theme.css: G7MYUTXKJS6WEMZT7P6LW5VNZKGG5TTJ
  forms:
    Form1: GRVXLXDHTB57JIRSRTZRCIJXCPSB63FQ
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '174298416669953332994248.225464'
